services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  logger-service:
    build: ./logger-service
    env_file: ./logger-service/.development.env
    depends_on:
      - redis

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    env_file: ./api-gateway/.development.env
    depends_on:
      - redis
      - logger-service

  identity-service:
    build: ./identity-service
    ports:
      - "8001:8001"
    env_file: ./identity-service/.development.env
    depends_on:
      - redis
      - api-gateway
      - logger-service

  url-service:
    build: ./url-service
    ports:
      - "8002:8002"
    env_file: ./url-service/.development.env
    depends_on:
      - redis
      - api-gateway
      - identity-service
      - logger-service
