services:
  postgres:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "secret"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db-managment:
    build: ./db-managment
    env_file: ./db-managment/.development.env
    depends_on:
      - postgres

  logger-service:
    build: ./logger-service
    env_file: ./logger-service/.development.env
    depends_on:
      - redis

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    env_file: ./api-gateway/.development.env
    depends_on:
      - redis
      - logger-service

  identity-service:
    build: ./identity-service
    ports:
      - "8001:8001"
    env_file: ./identity-service/.development.env
    depends_on:
      - redis
      - postgres
      - db-managment
      - api-gateway
      - logger-service

  url-service:
    build: ./url-service
    ports:
      - "8002:8002"
    env_file: ./url-service/.development.env
    depends_on:
      - redis
      - postgres
      - db-managment
      - api-gateway
      - identity-service
      - logger-service
